name = "RadioPropagation"
uuid = "b7825cb4-7108-404a-9145-f310ea34db32"
authors = ["Erik Buer <buer94@gmail.com>"]
version = "0.1.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test", "Documenter"]
